name: shins-builder

on:
  push:
    branches: [ master ]
    paths: 
    - '.github/workflows/shins.yml' 
    - 'docs/swagger.yaml'
    - 'docs/openapi.yaml'
    - 'docs/shins/resources/**'

jobs:
  shins-builder:
    env:
        openapi_path: ./docs/swagger.yaml
        shins_output_path: ./docs/shins
        shins_resources_path: ./docs/shins/resources
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install and run Widdershins
      run: |
        npm install widdershins -g
        widdershins $openapi_path -o $shins_resources_path/shins/source/index.html.md --expandBody --user_templates $shins_resources_path/templates_widder --summary
    - name: Install shins
      run: |
        git init ../shins
        cd ../shins
        git pull https://github.com/Mermade/shins
        npm install
    - name: Run shins
      run: |
        cp -r $shins_resources_path/shins/. ../shins -v
        cd ../shins
        node shins.js --inline --customcss
    - name: Push new build
      continue-on-error: true
      run: |
        cp ../shins/index.html $shins_output_path/index.html
        git config --local user.email "actions@example.com"
        git config --local user.name "github actions"
        git add $shins_output_path/index.html
        git commit -m "shins update"
        git push
      env:
        CI: true
